module.exports = {
  address: {
    street:  '4175 Palmero Dr',
    city:    'Los Angeles',
    state:   'CA',
    zip:     '90065',
    full:    '4175 Palmero Dr, Los Angeles, CA 90065',
  },
  neighborhood:      'Mount Washington',
  crossNeighborhood: 'Highland Park',
  region:            'NELA',

  // Property details
  price:     '$1,295,000',
  beds:      3,
  baths:     2.5,
  sqft:      1842,
  lot:       '10,145 sq ft',
  yearBuilt: 1956,
  garage:    '2-car garage',

  // Running ticker items
  tickerItems: [
    '3 BD / 2.5 BA',
    '1,842 sq ft',
    'Built 1956',
    'Mount Washington',
    'Highland Park Adjacent',
    'Los Angeles 90065',
    '$1,295,000',
    '10,145 sq ft lot',
    '2-Car Garage',
    'Corner Lot',
    'NELA',
    'Views',
  ],

  // Giveaway
  smsKeyword:    'PALMERO',
  smsNumber:     '(888) 900-7501',
  giveawayPrize: '$50 gift card to Wild Crust Pizza',

  // Site identity
  siteUrl:  'https://4175palmero.textmarco.com',
  siteName: '4175 Palmero Dr — Mount Washington, Los Angeles',

  // 30 rotating keywords for daily article generation
  keywords: [
    'things to do in highland park los angeles',
    'mount washington neighborhood guide los angeles',
    'highland park real estate market 2026',
    'best restaurants highland park LA',
    'avenue 50 highland park los angeles',
    'figueroa street highland park coffee and shops',
    'york boulevard highland park guide',
    'northeast los angeles neighborhoods overview',
    'NELA real estate investment 2026',
    'highland park history and gentrification los angeles',
    'mount washington elementary school los angeles',
    'hiking trails mount washington los angeles',
    'highland park arts scene los angeles',
    'moving to highland park los angeles guide',
    'highland park vs echo park los angeles',
    'northeast LA coffee shops and cafes',
    'highland park farmers market los angeles',
    'northeast LA commute to downtown los angeles',
    'highland park schools and education los angeles',
    'highland park craftsman bungalow architecture',
    'los angeles 90065 zip code neighborhood guide',
    'highland park nightlife bars and restaurants',
    'northeast LA dog friendly parks',
    'living in mount washington vs silver lake los angeles',
    'highland park local businesses and shopping',
    'mount washington views los angeles',
    'highland park property values 2026',
    'los angeles northeast neighborhood culture',
    'highland park weekend guide los angeles',
    'ernest e debs regional park los angeles hiking',
  ],
};
