module.exports = {
  address: {
    street:  '4175 Palmero Dr',
    city:    'Los Angeles',
    state:   'CA',
    zip:     '90065',
    full:    '4175 Palmero Dr, Los Angeles, CA 90065',
  },
  neighborhood:      'Mount Washington',
  crossNeighborhood: 'Highland Park',
  region:            'NELA',

  // Property details
  price:     '$1,295,000',
  beds:      3,
  baths:     2.5,
  sqft:      1536,
  lot:       '11,750 sq ft',
  yearBuilt: 1956,
  garage:    '2-car garage',

  // Running ticker items
  tickerItems: [
    '3 BD / 2.5 BA',
    '1,536 sq ft',
    'Built 1956',
    'Mount Washington',
    'Highland Park Adjacent',
    'Los Angeles 90065',
    '$1,295,000',
    '11,750 sq ft lot',
    '2-Car Garage',
    'Corner Lot',
    'NELA',
    'Views',
  ],

  // Giveaway
  smsKeyword:    'PALMERO',
  smsNumber:     '(888) 900-7501',
  giveawayPrize: '$50 gift card to Wild Crust Pizza',

  // Site identity
  siteUrl:  'https://4175palmero.textmarco.com',
  siteName: '4175 Palmero Dr — Mount Washington, Los Angeles',

  // 30 rotating keywords for daily article generation
  keywords: [
    'mid century modern homes los angeles',
    'mount washington neighborhood guide los angeles',
    'mid century homes highland park los angeles',
    'best restaurants highland park LA',
    'mid century architecture los angeles neighborhoods',
    'figueroa street highland park coffee and shops',
    'york boulevard highland park guide',
    'northeast los angeles mid century real estate',
    'NELA mid century homes 2026',
    'highland park history los angeles',
    'mount washington los angeles living',
    'hiking trails mount washington los angeles',
    'mid century traditional home los angeles',
    'moving to highland park los angeles guide',
    'highland park vs echo park los angeles',
    'northeast LA coffee shops and cafes',
    'highland park farmers market los angeles',
    'mid century home design features los angeles',
    'highland park schools and education los angeles',
    'mid century homes mount washington los angeles',
    'los angeles 90065 zip code neighborhood guide',
    'highland park nightlife bars and restaurants',
    'northeast LA dog friendly parks',
    'living in mount washington vs silver lake los angeles',
    'mid century real estate los angeles 2026',
    'mount washington views los angeles',
    'mid century home renovation los angeles',
    'los angeles northeast neighborhood culture',
    'highland park weekend guide los angeles',
    'mid century single level homes los angeles',
  ],
};
